In [1]:
# Step 1: Data loading and seperating features from target

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
data = pd.read_csv('c:/data/bike_rides.csv', sep = ",")
data['power_scale']=data['power']

t = 170


for i in range(len(data['power'])):
    if data['power'][i]>=t:


          data['power_scale'][i]=0
    
    elif data['power'][i]<t:

         data['power_scale'][i]=1

    
features = data[['heart-rate', 'cadence', 'speed', 'acceleration', 'slope']]

target=data['power_scale']


# Step 2: data splitting in train and test datasets

from sklearn.model_selection import train_test_split 
(X_train, X_test, y_train, y_test) = train_test_split(features, target, test_size=0.33,
 random_state=None)

# Step 3 feature selection

from sklearn.feature_selection import RFE
from sklearn.ensemble import ExtraTreesClassifier
estimator = ExtraTreesClassifier()
selector=RFE(estimator, n_features_to_select=4, step=1)
selector = selector.fit(X_train, y_train)
selector.support_ 
selector.ranking_
selector.score(X_test, y_test)
features_selected = selector.get_feature_names_out()




# Step 4: Model Training & Testing


from sklearn.ensemble import ExtraTreesClassifier
from sklearn.metrics import classification_report, confusion_matrix

X_train_selected=selector.transform(X_train)
X_test_selected=selector.transform(X_test)

estimator = ExtraTreesClassifier()
model = estimator.fit(X_train_selected, y_train)

preds = model.predict(X_test_selected)


selector.score(X_test, y_test), model.score(X_test_selected, y_test)






C:\Users\iliak\AppData\Local\Temp\ipykernel_27040\304410608.py:20: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['power_scale'][i]=1
C:\Users\iliak\AppData\Local\Temp\ipykernel_27040\304410608.py:16: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['power_scale'][i]=0


(0.8237484157160964, 0.8246989860583016)

In [2]:
from sklearn.metrics import confusion_matrix
confusion_matrix(preds, y_test, normalize = 'true')

array([[0.83241506, 0.16758494],
       [0.19248466, 0.80751534]])

In [3]:
model.predict_proba(X_test_selected)

array([[0.62, 0.38],
       [0.96, 0.04],
       [1.  , 0.  ],
       ...,
       [0.17, 0.83],
       [0.89, 0.11],
       [0.99, 0.01]])

In [4]:
model.predict(X_test_selected)

array([0., 0., 0., ..., 1., 0., 0.])

In [5]:
features_selected = selector.get_feature_names_out()
features_selected

array(['heart-rate', 'cadence', 'speed', 'acceleration'], dtype=object)

In [6]:
selector.ranking_

array([1, 1, 1, 1, 2])

In [7]:
model.feature_importances_

array([0.22824162, 0.33941484, 0.22293706, 0.20940647])

In [113]:
heart_rate_test = 180
cadence_test=90
speed_test=30
acceleration_test=0.02
slope_test=10

test_array=np.array([[heart_rate_test,  speed_test, acceleration_test, slope_test]])



In [114]:
d={'heart-rate': pd.Series([heart_rate_test]), 'cadence': pd.Series([cadence_test])
,'speed':pd.Series([speed_test]),'acceleration':pd.Series([acceleration_test]), 'slope':pd.Series([slope_test])}
df=pd.DataFrame(d)[features_selected]
df

heart-rate  cadence  speed  acceleration
0         180       90     30          0.02

In [115]:
model.predict(np.array(df))

array([0.])

In [116]:
model.predict_proba(np.array(df))

array([[0.76, 0.24]])

In [117]:
data.describe()

power    heart-rate       cadence         speed  acceleration  \
count  38254.000000  38254.000000  38254.000000  38254.000000  38254.000000   
mean     192.847781    141.385616     72.896876      8.203325     -0.002056   
std      116.760026     16.562215     25.235907      2.603563      0.225916   
min        0.000000     66.000000      0.000000      0.000000     -2.384600   
25%      134.000000    131.000000     73.000000      6.579000     -0.074400   
50%      199.000000    142.000000     82.000000      8.297000      0.005800   
75%      248.000000    153.000000     87.000000      9.874000      0.083800   
max      901.000000    187.000000    107.000000     18.604000      1.311400   

              slope   power_scale  
count  38254.000000  38254.000000  
mean       0.005646      0.360956  
std        0.108174      0.480284  
min       -7.731092      0.000000  
25%        0.000000      0.000000  
50%        0.000000      0.000000  
75%        0.010134      1.000000  
max       14.857143      1.000000